name: Pull request validation

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-main-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  screenshot-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run screenshot tests
        id: screenshot-tests
        run: ./gradlew verifyPaparazziDebug --continue

      - name: Upload artifact 1
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshot-report1
          path: /home/runner/work/ScreenshotTests/ScreenshotTests/**/build/reports/tests/testDebugUnitTest/

      - name: Process failed screenshot tests
        if: failure()
        id: failed-screenshots
        run: "./.github/workflows/process_failed_screenshot_tests.sh"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          PULL_REQUEST_BRANCH: ${{ github.head_ref }}

      - name: Create an issue if screenshot tests failed
        uses: octokit/request-action@v2.1.9
        if: always() && steps.failed-screenshots.outputs.PULL_REQUEST_COMMENT
        with:
          route: POST /repos/:repo/issues/:issue_number/comments
          repo: ${{ github.repository }}
          issue_number: ${{ steps.failed-screenshots.outputs.PULL_REQUEST_NUMBER }}
          body: ${{ steps.failed-screenshots.outputs.PULL_REQUEST_COMMENT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact 2
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshot-report2
          path: /home/runner/work/ScreenshotTests/ScreenshotTests/**/build/reports/tests/testDebugUnitTest/
